/**
 * Joi Schema to validate the Song model
 */
const Joi = require('joi');

const SongSchema = Joi.object({
  id: [Joi.allow(null), Joi.string()], // id will be generated by system
  title: Joi.string().required(),
  year: Joi.number().max(2099).required(),
  performer: Joi.string().required(),
  genre: Joi.string().required(),
  duration: [Joi.allow(null), Joi.number()],
  albumId: [Joi.allow(null), Joi.string()],
});

module.exports = { SongSchema };
