/**
 * Joi Schema to validate the Album model
 */
const Joi = require('joi');

const SongSchema = Joi.object({
  id: [Joi.allow(null), Joi.string()], // id will be generated by system
  name: Joi.string().required(),
  year: Joi.number().max(2099).required(),
  songs: [
    Joi.allow(null),
    Joi.array().items(
      Joi.object({
        id: [Joi.allow(null), Joi.string()], // id of the song
        title: Joi.string().required(),
        performer: Joi.string().required(),
      }),
    ),
  ],
});

module.exports = { SongSchema };
